uploads = []

[[generated]]
id = "0Ujc1kZNZguTId39C7F0h"
uri = "file://artifacts/paris-planner-mobile/assets/images/icon.png"
type = "image"
title = "paris planner mobile icon"

[[outputs]]
id = "IPxm4VV7Ragpf2Wus5KeN"
uri = "file://README.md"
type = "text"
title = "README.md"
